### ISSUE TITLE
HookWebpackError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by TkaczykAdam** [remorses/next-superjson#1]
Hello,

 I am getting this error on the startup of my nextJS application.
 
 ```
 HookWebpackError: Cannot read property 'replace' of undefined
 ```

 ```js
// next.config.js

// other next config

const tmModules = ['next-connect', 'js-cookie', 'swiper', 'react-markdown']

// eslint-disable-next-line @typescript-eslint/no-var-requires
const withNextTranspileModules = require('next-transpile-modules')(tmModules, {
  resolveSymlinks: true,
  debug: false
})
let config = withNextTranspileModules(nextConfig)
// This throws an error
// config = withSuperjson(config)

if (process.env.NEXT_PUBLIC_SENTRY_DSN) {
  config = withSentryConfig(config)
}

module.exports = config
```

 My package manager is Yarn Berry with PnP.
 Maybe it's because of `next-transpile-modules`?

**Comment by remorses** [comment]
Can you append the full error stack trace?

**Comment by TkaczykAdam** [comment]
Sure

```
HookWebpackError: Cannot read property 'replace' of undefined
    at makeWebpackError (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:47121:9)
    at /home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:31041:12
    at eval (eval at create (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:141201:10), <anonymous>:12:1)
    at fn (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:28464:17)
    at Hook.eval [as callAsync] (eval at create (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:141201:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:141003:14)
    at cont (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:31038:34)
    at /home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:31086:10
    at symbolIterator (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/neo-async/async.js:1:14452)
    at done (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/neo-async/async.js:1:14832)
-- inner error --
TypeError: Cannot read property 'replace' of undefined
    at PagesManifestPlugin.createAssets (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:35:47)
    at /home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:47:22
    at fn (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:28462:10)
    at Hook.eval [as callAsync] (eval at create (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:141201:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:141003:14)
    at cont (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:31038:34)
    at /home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:31086:10
    at symbolIterator (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/neo-async/async.js:1:14452)
    at done (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/neo-async/async.js:1:14832)
    at /home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/neo-async/async.js:1:9438
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read property 'replace' of undefined
    at PagesManifestPlugin.createAssets (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:35:47)
    at /home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:47:22
    at fn (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:28462:10)
    at Hook.eval [as callAsync] (eval at create (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:141201:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:141003:14)
    at cont (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:31038:34)
    at /home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/webpack/bundle5.js:31086:10
    at symbolIterator (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/neo-async/async.js:1:14452)
    at done (/home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/neo-async/async.js:1:14832)
    at /home/adam/projects/grupa-zero/fast-food/.yarn/__virtual__/next-virtual-5777263b8f/0/cache/next-npm-12.0.4-fcbd6e5d3e-b9711e7d42.zip/node_modules/next/dist/compiled/neo-async/async.js:1:9438
error - HookWebpackError: Cannot read property 'replace' of undefined
```

**Comment by remorses** [comment]
You have to call withSuperjson like this
`module.exports = withSuperjson()({})`
